server:
  port: 8768

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  application:
    name: config-server

  profiles:
    active: native

  cloud:
    config:
      server:
        git:
          uri: https://github.com/LinkinStars/SpringCloudTemplate
          search-paths: SpringCloudConfig
          default-label: master
          username:
          password:
      fail-fast: true
