server:
  port: 8765

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

spring:
  freemarker:
    prefer-file-system-access: false
  application:
    name: feign-service


feign:
  hystrix:
    enabled: true
