server:
  port: 8763

eureka:
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: service-provider

#eureka:
#  client:
#  healthcheck:
#    enabled: true
#  instance:
#    lease-expiration-duration-in-seconds: 30
#lease-renewal-interval-in-seconds: 10